FROM golang:latest

RUN mkdir /app
WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

RUN 
Learn more about the "RUN " Dockerfile command.
go build -o /docker-gs-ping

CMD ["./crud"]